# Generated by Django 2.0.7 on 2018-08-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.TextField(null=True),
        ),
    ]
