# Generated by Django 2.0.8 on 2018-08-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaanalytics', '0002_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
