# Generated by Django 4.0.5 on 2022-06-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaanalytics', '0003_auto_20180806_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
